version: '3.8'

services:
  frontend:
    container_name: react
    build:
      context: .
    ports:
      - "3000:80"
  
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "5000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend